services:
  postgres:
    container_name: sql-for-dev_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-28010}:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres_gis:
    container_name: sql-for-dev_postgres_gis_container
    image: postgis/postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
      PGDATA: /data/postgres
    volumes:
       - postgres_gis:/data/postgres
    ports:
      - "${POSTGRES_PORT:-28020}:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: sql-for-dev_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-samwizardry@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-P@ssw0rd}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-28001}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    postgres_gis:
    pgadmin: